#! /bin/sh

xsetroot -cursor_name left_ptr

pgrep -x sxhkd > /dev/null || sxhkd &

feh --bg-fill --randomize  ~/Pictures/wall/ &
pkill picom; picom --experimental-backends --no-use-damage &
~/.config/polybar/launch.sh &




bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.50

bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
